name: build and deploy artifact to gh-pages branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - run: yarn install
      - run: yarn run test
      - run: yarn run generate

      - name: create .well-known folder
        run: mkdir -p ./dist/.well-known
      - run: echo '${{ secrets.BRAVE_REWARDS_VERIFICATION }}' > ./dist/.well-known/brave-rewards-verification.txt

      - run: echo '${{ secrets.GOOGLE_SITE_VERIFICATION_CONTENT }}' > './dist/${{ secrets.GOOGLE_SITE_VERIFICATION_FILE_NAME }}'

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: theshrine.pw
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
