name: test and build

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: "yarn"

      - run: yarn install
      - run: yarn run test
      - run: yarn run generate
